stages:
  - build
  - test

npm_test:
  stage: build
  image: node:22-alpine
  script:
    - node --version
    - npm install
    - npm ci
    - npm run build

  artifacts:
    paths:
      - build/

py_test:
  stage: build
  image: python:3.12-alpine
  script:
    - python --version
    - pip install --upgrade pip
    - pip install build
    - pip run build
