variables:
  NETLIFY_SITE_ID: "7924d100-467c-4fe6-912d-c16cdd178bd3"
  TF_ROOT: "."

stages:
  - build
  - test
  - unit
  - deploy_stg
  - deploy_prod
  - validate
  - plan
  - apply

.npm_build:
  stage: build
  image: node:22-alpine
  script:
    - node --version
    - npm install
    - npm ci
    - npm run build

  artifacts:
    paths:
      - build/

.npm_test_artifacts:
  stage: test
  image: node:22-alpine
  dependencies:
    - npm_build
  script:
    - test -f build/index.html

.unit_test:
  stage: test
  image: node:22-alpine
  script:
    - npm install
    - npm ci
    - npm test
  artifacts:
    when: always
    reports:
      junit: reports/junit.xml

.netlify_stg:
  image: node:22-alpine
  stage : deploy_stg
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - npm install -g netlify-cli@20.1.1
    - netlify --version
    - netlify status
    - echo "Deploying to Netlify $NETLIFY_SITE_ID"
    - netlify deploy --alias staging --dir build

.netlify_prod:
  image: node:22-alpine
  stage : deploy_prod
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - npm install -g netlify-cli@20.1.1
    - netlify --version
    - netlify status
    - echo "Deploying to Netlify $NETLIFY_SITE_ID"
    - netlify deploy --prod --dir build
    - apk add curl
    - curl "https://bhekani-tut.netlify.app" | grep 'GitLab'


.py_test:
  stage: build
  image: python:3.12-alpine
  script:
    - python --version
    - pip install --upgrade pip
    - pip install build
    - python src/hello.py

.aws_s3:
  stage: .pre
  image: 
    name: amazon/aws-cli
    entrypoint: ['']
  variables:
    region: 'af-south-1'
  script:
    - aws --version
    - aws s3 ls

.terraform_validate:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  stage: validate
  script:
    - terraform validate

.terraform_plan:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  stage: plan
  variables:
    GITLAB_ACCESS_TOKEN: $TOKEN
    TF_STATE_NAME: "default"
  artifacts:
    paths: 
      - /build
  script:
    - cd src/
    - export HTTP_PASSWORD=$TOKEN
    - terraform init
    - terraform plan

terraform_plan:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  stage: plan
  artifacts:
    paths: 
      - /build
  variables:
    TF_STATE_NAME: "default"
  script:
    - cd src/
    - export HTTP_HEADER_PRIVATE_TOKEN="$TOKEN"
    - export TF_STATE_NAME=default
    - echo "$TOKEN"
    - terraform init -backend-config="address=https://gitlab.com/api/v4/projects/78204586/terraform/state/$TF_STATE_NAME" -backend-config="lock_address=https://gitlab.com/api/v4/projects/78204586/terraform/state/$TF_STATE_NAME/lock" -backend-config="unlock_address=https://gitlab.com/api/v4/projects/78204586/terraform/state/$TF_STATE_NAME/lock" -backend-config="username=bhekani.mdletsher" -backend-config="password=$GITLAB_ACCESS_TOKEN" -backend-config="lock_method=POST" -backend-config="unlock_method=DELETE" -backend-config="retry_wait_min=5"
    - terraform plan

.terraform_apply:
  image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  stage: apply
  variables:
    GITLAB_ACCESS_TOKEN: $TOKEN
    TF_STATE_NAME: "default"
  artifacts:
    paths: 
      - /build
  script:
    - export HTTP_PASSWORD=$TOKEN
    - terraform init -backend-config="address=https://gitlab.com/api/v4/projects/78204586/terraform/state/$TF_STATE_NAME" -backend-config="lock_address=https://gitlab.com/api/v4/projects/78204586/terraform/state/$TF_STATE_NAME/lock" -backend-config="unlock_address=https://gitlab.com/api/v4/projects/78204586/terraform/state/$TF_STATE_NAME/lock" -backend-config="username=bhekani.mdletsher"-backend-config="password=$GITLAB_ACCESS_TOKEN" -backend-config="lock_method=POST" -backend-config="unlock_method=DELETE" -backend-config="retry_wait_min=5"
    - cd src/
    - terraform init
    - terraform apply -auto-approve

