stages:
  - build
  - test
  - unit

npm_build:
  stage: build
  image: node:22-alpine
  script:
    - node --version
    - npm install
    - npm ci
    - npm run build

  artifacts:
    paths:
      - build/

npm_test_artifacts:
  stage: test
  image: node:22-alpine
  dependencies:
    - npm_build
  script:
    - test -f build/index.html

unit_test:
  stage: test
  image: node:22-alpine
  script:
    - npm install
    - npm ci
    - npm test
  artifacts:
    when: always
    reports:
      junit: reports/junit.xml


py_test:
  stage: build
  image: python:3.12-alpine
  script:
    - python --version
    - pip install --upgrade pip
    - pip install build
    - python src/hello.py
