pipeline {
   agent {
      docker {
         image 'hashicorp/terraform:1.15'
         args '-v root'
      }
   }
   environment {
      cred = credentials('aws-key')
   }
   stages {
      stage ('Say Hi') {
         steps {
            echo 'Hello world, please run!'
         }
      }

      stage ('configure aws')
      {
         steps {
            withCredentials([usernamePassword(credentialsId: 'aws-key', passwordVariable: 'AWS_SECRET_ACCESS_KEY', usernameVariable: 'AWS_ACCESS_KEY_ID')]) {
               sh 'aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID'
               sh 'aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY'
            }
         }
      }

      stage('Checkout'){
         steps {
            checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Bhekanisphe/learn-git.git']])
         }
      }
      stage ("Terraform Init"){
         steps{
            dir("src"){
            sh 'terraform init'
            }
         }
      }
      stage ("Terraform Plan"){
         steps{
            dir("src"){
            sh 'terraform plan'
            }
         }
      }
      stage ("Terraform Apply"){
         steps{
            dir("src"){
            sh 'terraform apply -auto-approve'
            }
         }
      }
   }
}
