pipeline {
   agent any
   environment {
      cred = credentials('aws-key')
   }
   stages {
      stage ('Say Hi') {
         steps {
            echo 'Hello world, please run!'
         }
      }
      stage('Checkout'){
         steps {
            checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Bhekanisphe/learn-git.git']])
         }
      }
      stage ("Terraform Init"){
         steps{
            dir("src"){
            sh 'terraform init'
            }
         }
      }
      stage ("Terraform Plan"){
         steps{
            sh 'terraform plan'
         }
      }
      stage ("Terraform Apply"){
         steps{
            sh 'terraform apply'
         }
      }
   }
}
